In [1]:
import numpy as np
from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs

# Generate synthetic data
X, _ = make_blobs(n_samples=1000, n_features=5, random_state=42)

# Standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Randomized PCA
randomized_pca = PCA(n_components=2, svd_solver='randomized', random_state=42)
X_randomized_pca = randomized_pca.fit_transform(X_scaled)

print("Randomized PCA Components:")
print(randomized_pca.components_)

# Incremental PCA (batch size of 100)
incremental_pca = IncrementalPCA(n_components=2)
for batch in np.array_split(X_scaled, 10):  # Splitting data into 10 batches
    incremental_pca.partial_fit(batch)

X_incremental_pca = incremental_pca.transform(X_scaled)

print("\nIncremental PCA Components:")
print(incremental_pca.components_)


Randomized PCA Components:
[[-0.15336137 -0.60291665  0.43209116  0.24728533  0.60425077]
 [ 0.65579452 -0.11140889 -0.38625915  0.63497614  0.07162944]]

Incremental PCA Components:
[[-0.15140083 -0.60178383  0.43601879  0.24785611  0.60281753]
 [ 0.65660378 -0.11118047 -0.38492501  0.63503451  0.07123399]]
